require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityKeepAwake', :path => '../../node_modules/@capacitor-community/keep-awake'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapgoBackgroundGeolocation', :path => '../../node_modules/@capgo/background-geolocation'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  # Unity Ads SDK（リワード動画・フッターバナー）。Android の build.gradle の
  # com.unity3d.ads:unity-ads に対応する iOS 版。UnityAdsPlugin.swift から使う。
  pod 'UnityAds', '~> 4.18'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
